// Code generated by qtc from "base.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line templates/base.qtpl:1
package templates

//line templates/base.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/base.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/base.qtpl:2
type Page interface {
//line templates/base.qtpl:2
	Title() string
//line templates/base.qtpl:2
	StreamTitle(qw422016 *qt422016.Writer)
//line templates/base.qtpl:2
	WriteTitle(qq422016 qtio422016.Writer)
//line templates/base.qtpl:2
	Body() string
//line templates/base.qtpl:2
	StreamBody(qw422016 *qt422016.Writer)
//line templates/base.qtpl:2
	WriteBody(qq422016 qtio422016.Writer)
//line templates/base.qtpl:2
}

//line templates/base.qtpl:8
func StreamPageTemplate(qw422016 *qt422016.Writer, p Page) {
//line templates/base.qtpl:8
	qw422016.N().S(`
<html>
	<head>
		<title>`)
//line templates/base.qtpl:11
	p.StreamTitle(qw422016)
//line templates/base.qtpl:11
	qw422016.N().S(`</title>
	</head>
	<body>
		<div>
			<a href="/">return to main page</a>
		</div>
		`)
//line templates/base.qtpl:17
	p.StreamBody(qw422016)
//line templates/base.qtpl:17
	qw422016.N().S(`
	</body>
</html>
`)
//line templates/base.qtpl:20
}

//line templates/base.qtpl:20
func WritePageTemplate(qq422016 qtio422016.Writer, p Page) {
//line templates/base.qtpl:20
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/base.qtpl:20
	StreamPageTemplate(qw422016, p)
//line templates/base.qtpl:20
	qt422016.ReleaseWriter(qw422016)
//line templates/base.qtpl:20
}

//line templates/base.qtpl:20
func PageTemplate(p Page) string {
//line templates/base.qtpl:20
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/base.qtpl:20
	WritePageTemplate(qb422016, p)
//line templates/base.qtpl:20
	qs422016 := string(qb422016.B)
//line templates/base.qtpl:20
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/base.qtpl:20
	return qs422016
//line templates/base.qtpl:20
}
