// Code generated by qtc from "index.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line templates/index.qtpl:1
package templates

//line templates/index.qtpl:1
import "github.com/qiangxue/fasthttp-routing"

//line templates/index.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/index.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/index.qtpl:4
type MainPage struct {
	CTX *routing.Context
}

//line templates/index.qtpl:9
func (p *MainPage) StreamTitle(qw422016 *qt422016.Writer) {
//line templates/index.qtpl:9
	qw422016.N().S(`
Jack Greenberg | Electrical Engineer
`)
//line templates/index.qtpl:11
}

//line templates/index.qtpl:11
func (p *MainPage) WriteTitle(qq422016 qtio422016.Writer) {
//line templates/index.qtpl:11
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/index.qtpl:11
	p.StreamTitle(qw422016)
//line templates/index.qtpl:11
	qt422016.ReleaseWriter(qw422016)
//line templates/index.qtpl:11
}

//line templates/index.qtpl:11
func (p *MainPage) Title() string {
//line templates/index.qtpl:11
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/index.qtpl:11
	p.WriteTitle(qb422016)
//line templates/index.qtpl:11
	qs422016 := string(qb422016.B)
//line templates/index.qtpl:11
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/index.qtpl:11
	return qs422016
//line templates/index.qtpl:11
}

//line templates/index.qtpl:14
func (p *MainPage) StreamBody(qw422016 *qt422016.Writer) {
//line templates/index.qtpl:14
	qw422016.N().S(`
	<h1>Main page</h1>
	<div>
		Click links below:
		<ul>
			<li><a href="/unknown-page">Error page</a></li>
		</ul>
	</div>
	<div>
		Some info about you:<br/>
	</div>
`)
//line templates/index.qtpl:25
}

//line templates/index.qtpl:25
func (p *MainPage) WriteBody(qq422016 qtio422016.Writer) {
//line templates/index.qtpl:25
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/index.qtpl:25
	p.StreamBody(qw422016)
//line templates/index.qtpl:25
	qt422016.ReleaseWriter(qw422016)
//line templates/index.qtpl:25
}

//line templates/index.qtpl:25
func (p *MainPage) Body() string {
//line templates/index.qtpl:25
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/index.qtpl:25
	p.WriteBody(qb422016)
//line templates/index.qtpl:25
	qs422016 := string(qb422016.B)
//line templates/index.qtpl:25
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/index.qtpl:25
	return qs422016
//line templates/index.qtpl:25
}
